// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsx11D2Hfyl_LyXEUbRWPsYGOOAmLe5W0',
    appId: '1:551081453608:web:bdadc8d58c82bc53182d1d',
    messagingSenderId: '551081453608',
    projectId: 'ssws-d7770',
    authDomain: 'ssws-d7770.firebaseapp.com',
    storageBucket: 'ssws-d7770.firebasestorage.app',
    measurementId: 'G-QS511DFP01',
    databaseURL: 'https://ssws-d7770-default-rtdb.europe-west1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9oQhZ0fhwIhQGpfzX07-jf3W_YSYT6pA',
    appId: '1:551081453608:android:a5874fa074ef2192182d1d',
    messagingSenderId: '551081453608',
    projectId: 'ssws-d7770',
    storageBucket: 'ssws-d7770.firebasestorage.app',
    databaseURL: 'https://ssws-d7770-default-rtdb.europe-west1.firebasedatabase.app',
  );
}
